language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
branches:
  only:
  - backend
script:
  - yarn start
before_install:
- openssl aes-256-cbc -K $encrypted_9b2d7e19d83c_key -iv $encrypted_9b2d7e19d83c_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
addons:
  ssh_known_hosts: 106.14.174.206